// <auto-generated />
namespace Nursery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201903150444469_migration_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
